var LOBBYING_SUMMARY_URL='https://raw.githubusercontent.com/ReporterAdam/Tennessee-Lookout-Cash-For-Clout-Political-Spending-database/main/lobbying_summary.csv';
var LOBBYING_REPORTS_URL='https://raw.githubusercontent.com/ReporterAdam/Tennessee-Lookout-Cash-For-Clout-Political-Spending-database/main/lobbying_reports.csv';
var summaryData=[],reportsData=[],openRow=null;
function parseCSV(text){var lines=text.trim().split('\n');var headers=lines[0].split(',').map(function(h){return h.trim().replace(/"/g,'');});return lines.slice(1).map(function(line){var cols=[],current='',inQuotes=false;for(var i=0;i<line.length;i++){if(line[i]==='"'){inQuotes=!inQuotes;}else if(line[i]===','&&!inQuotes){cols.push(current.trim());current='';}else{current+=line[i];}}cols.push(current.trim());var obj={};headers.forEach(function(h,i){obj[h]=cols[i]||'';});return obj;});}
function fmtMoney(n){n=parseFloat(n)||0;if(n>=1000000)return'$'+(n/1000000).toFixed(1)+'M';if(n>=1000)return'$'+Math.round(n/1000)+'K';return'$'+Math.round(n).toLocaleString();}
function buildTable(data){var body=document.getElementById('lobbying-body');body.innerHTML='';if(data.length===0){body.innerHTML='<tr><td colspan="3" style="padding:20px;text-align:center;color:#aaa;">No results found</td></tr>';return;}data.forEach(function(row,i){var tr=document.createElement('tr');tr.style.borderBottom='1px solid #eee';tr.style.cursor='pointer';tr.innerHTML='<td style="padding:10px;font-weight:500;">'+row.company_name+'<span id="chev-'+i+'" style="margin-left:6px;font-size:10px;color:#aaa;">&#9654;</span></td><td style="padding:10px;text-align:right;font-variant-numeric:tabular-nums;">'+fmtMoney(row.total_all)+'</td><td style="padding:10px;text-align:right;font-variant-numeric:tabular-nums;">'+fmtMoney(row.total_since_2021)+'</td>';tr.onmouseenter=function(){this.style.background='#f9f9f9';};tr.onmouseleave=function(){this.style.background='';};tr.onclick=function(){toggleDrillDown(row.company_name,i,this);};body.appendChild(tr);var expTr=document.createElement('tr');expTr.id='exp-'+i;expTr.style.display='none';var expTd=document.createElement('td');expTd.colSpan=3;expTd.style.padding='0';expTd.style.background='#f9f9f9';expTd.style.borderBottom='2px solid #eee';expTd.innerHTML='<div id="exp-inner-'+i+'" style="padding:16px 20px;"></div>';expTr.appendChild(expTd);body.appendChild(expTr);});}
function toggleDrillDown(companyName,i,tr){var expTr=document.getElementById('exp-'+i);var chev=document.getElementById('chev-'+i);var isOpen=expTr.style.display!=='none';if(openRow!==null&&openRow!==i){document.getElementById('exp-'+openRow).style.display='none';var oldChev=document.getElementById('chev-'+openRow);if(oldChev)oldChev.innerHTML='&#9654;';}if(isOpen){expTr.style.display='none';chev.innerHTML='&#9654;';openRow=null;}else{expTr.style.display='table-row';chev.innerHTML='&#9660;';openRow=i;renderDrillDown(companyName,i);}}
function renderDrillDown(companyName,i){var inner=document.getElementById('exp-inner-'+i);var reports=reportsData.filter(function(r){return r.company_name===companyName;});if(reports.length===0){inner.innerHTML='<p style="color:#aaa;font-size:13px;">No filing records found.</p>';return;}var html='<div style="font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#aaa;margin-bottom:10px;">Individual filings — '+companyName+'</div><table style="width:100%;border-collapse:collapse;font-size:13px;"><thead><tr style="border-bottom:1px solid #ddd;"><th style="text-align:left;padding:6px 8px;color:#888;font-size:11px;">Filing period</th><th style="text-align:left;padding:6px 8px;color:#888;font-size:11px;">Lobbyist compensation</th><th style="text-align:left;padding:6px 8px;color:#888;font-size:11px;">Related expenses</th></tr></thead><tbody>';reports.forEach(function(r){html+='<tr style="border-bottom:1px solid #f0f0f0;"><td style="padding:6px 8px;">'+r.filing_period_display+'</td><td style="padding:6px 8px;color:#444;">'+(r.lobbyist_compensation||'—')+'</td><td style="padding:6px 8px;color:#444;">'+(r.lobbying_related_expenses||'—')+'</td></tr>';});html+='</tbody></table>';inner.innerHTML=html;}
function filterLobbying(q){var lq=q.toLowerCase();var filtered=summaryData.filter(function(r){return r.company_name.toLowerCase().indexOf(lq)!==-1;});buildTable(filtered);}
Promise.all([fetch(LOBBYING_SUMMARY_URL).then(function(r){return r.text();}),fetch(LOBBYING_REPORTS_URL).then(function(r){return r.text();})]).then(function(results){summaryData=parseCSV(results[0]);reportsData=parseCSV(results[1]);buildTable(summaryData);}).catch(function(err){document.getElementById('lobbying-body').innerHTML='<tr><td colspan="3" style="padding:20px;text-align:center;color:#c00;">Failed to load data. Please try again later.</td></tr>';});